import { Sidebar } from "@/components/Sidebar";
import { useFavorites } from "@/context/FavoriteContext";
import styles from "./Favorites.module.scss";

import Head from "next/head";
import Image from "next/image";

export default function Favorites() {
  const { favorites, deleteFavorites } = useFavorites();

  return (
    <>
      <Head>
        <title>Food Delivery Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <div style={{ display: "flex" }}>
          <Sidebar />
          <div>
            <h1>Favorites</h1>
            {Object.keys(favorites).length >= 1 ? (
              Object.keys(favorites)?.map((productId) => {
                const favoriteItem = favorites[parseInt(productId)];
                if (!favoriteItem) {
                  return null;
                }
                const product = favoriteItem?.product;

                return (
                  <div key={productId} className={styles.cartItemWrapper}>
                    <Image
                      width="50"
                      height="50"
                      alt="pizza"
                      src={product?.image}
                      className={styles.image}
                      priority
                    />
                    <div
                      style={{
                        display: "flex",
                        flexDirection: "column",
                        width: "100%",
                        justifyContent: "center",
                        marginLeft: "10px",
                      }}
                    >
                      <p className={styles.itemName}>{product?.name}</p>
                      <div
                        style={{
                          display: "flex",
                          justifyContent: "space-between",
                        }}
                      >
                        <div className={styles.priceWrapper}>
                          <p className={styles.currency}>$</p>
                          <p className={styles.price}>{product.price}</p>
                        </div>
                      </div>
                      <p
                        className={styles.deleteButton}
                        onClick={() => deleteFavorites(product)}
                      >
                        Remove
                      </p>
                    </div>
                  </div>
                );
              })
            ) : (
              <p>No product in favorites</p>
            )}
          </div>
        </div>
      </main>
    </>
  );
}
