import { Cart } from "@/components/Cart";
import { Sidebar } from "@/components/Sidebar";
import { TodayMenu } from "@/components/TodayMenu";
import { Product } from "@/components/TodayMenu/CategoryTabs";
import { UserInfo } from "@/components/UserInfo";
import styles from "@/styles/Home.module.scss";

import Head from "next/head";
import { useState } from "react";

export default function Home() {
  const [cart, setCart] = useState<Product[]>([]);

  function handleAddToCart(product: Product) {
    setCart([...cart, product]);
  }

  return (
    <>
      <Head>
        <title>Food Delivery Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <div className={styles.mainBody}>
          <Sidebar />
          <TodayMenu handleAddToCart={handleAddToCart} />
          <div>
            <UserInfo />
            <Cart cart={cart} />
          </div>
        </div>
      </main>
    </>
  );
}
